[package]
name = "qugene"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
clap = { version = "4.4.12", features = ["cargo", "derive"] }
enum-display = "0.1.3"
rand = "0.8.5"
